name: "Build"
on:
  push:
    branches: ['main']
jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v10
        with:
          name: kubukoz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ./build.sh
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./result
