name: "Build"
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v11
        with:
          name: kubukoz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Test
        run: ./test.sh

      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: ./result
