name: "Build"
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v11
        with:
          name: kubukoz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build
        run: ./build.sh && cp --no-preserve=mode ./result public

      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: ./public
