name: "Build"
on:
  push:
    branches: ['master']
jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v16
      - run: nix-shell --command "bundle exec rake site:deploy"
