name: "Build"
on:
  push:
    branches: ['master']
jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v16
      - run: nix develop --command bundle exec jekyll build
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: _site
